name: CI to ACR and GitOps CD

on:
  push:
    branches: [ "main" ]

env:
  # Using github.sha gives us a unique, immutable tag for every commit
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-push-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout app code
        uses: actions/checkout@v4
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
